version: "3"
services:
  # petstore-backend:
  #   build:
  #     context: .
  #     dockerfile: backend/petstore/Dockerfile
  #   hostname: petstore-api
  #   ports:
  #     - 8888:8888
  #   restart: on-failure
  #   depends_on:
  #     - fullstack-postgres
  #   networks:
  #     - fullstack
  
  # petstore-frontend:
  #   build:
  #     context: .
  #     dockerfile: frontend/react-petstore/Dockerfile
  #   hostname: petStore-react
  #   ports:
  #     - 8080:8080
  #   restart: on-failure
  #   # volumes:
  #   #   - frontend/react-petstore/api:/usr/src/app/
  #   depends_on:
  #     - petstore-backend
  #   networks:
  #     - fullstack

  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack

volumes:
  # api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
